### ISSUE TITLE
Renderer should return string instead of fragments

### ISSUE THREAD

**Issue by chikeichan** [trio-dev/Trio#30]
Return HTML string instead of fragments for better cross-brower compatibility and isomorphic rendering

DoD:
-Create renderHTML method
-should return HTML String 
-see gist https://gist.github.com/chikeichan/6d4e09b6f045b5cd804b

**Comment by sdtsui** [comment]
Hey Jacky,

I'd like to work on this ticket.

Can you please whip up a Gist that uses `Renderer.render`? 
-Create 5 divs
-Call `.render` such that you're returning the fragments, and I can log them in console or terminal.

I think it would help me better understand how `Renderer` works, and should be faster than a hangout.

Thanks,
Dan

**Comment by chikeichan** [comment]
Updated DoD. Please see gist https://gist.github.com/chikeichan/6d4e09b6f045b5cd804b
